name: Build and deploy

on:
  push:
    tags:
      - v*

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm --prefix ./functions/ install --production
      - run: npm run build
      - run: npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
